version: '3.8'

services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ganache
    ports:
      - "8545:8545"
    networks:
      - caddy

networks:
  caddy:
    external: true

