version: '3.0'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
  mysql:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"
